[server]
port = 8080
bind_address = "0.0.0.0"
#TODO add TLS Configuration options

[datasources]
name = "static-grpc-alpha"
urls = ["http://localhost:9096", "http://localhost:9097"]
#TODO add TLS Configuration options

[debug]
log_level = "info"