[server]
port = 8080
bind_address = "0.0.0.0"
#TODO add TLS Configuration options

[datasources]
name = "static-http"
urls = ["http://localhost:3100", "http://localhost:3101"]
#TODO add TLS Configuration options

[debug]
log_level = "info"