name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: ./pkg

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.WORKING_DIR}}
    - name: Run tests
      run: cargo test --workspace --verbose
      working-directory: ${{env.WORKING_DIR}}
