name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: ./pkg

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@1.57.0
      name: Build
      with:
        args: cd ${{env.WORKING_DIR}} && cargo build
    - name: Run tests
      uses: icepuma/rust-action@1.57.0
      with:
        args: cd ${{env.WORKING_DIR}} && cargo test --workspace
